# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/LABAdmin/BRAMNN/BRAMNN.srcs/sources_1/ip/FCLW1/FCLW1.xci
# IP: The module: 'FCLW1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/LABAdmin/BRAMNN/BRAMNN.srcs/sources_1/ip/FCLW1/FCLW1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FCLW1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/LABAdmin/BRAMNN/BRAMNN.srcs/sources_1/ip/FCLW1/FCLW1.xci
# IP: The module: 'FCLW1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/LABAdmin/BRAMNN/BRAMNN.srcs/sources_1/ip/FCLW1/FCLW1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FCLW1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
